### ISSUE TITLE
helm 3.10.0

### ISSUE THREAD

**Issue by denisa** [lachie83/k8s-helm#109]
3.10.0 is now available: https://github.com/helm/helm/releases/tag/v3.10.0

**Comment by denisa** [comment]
https://github.com/lachie83/k8s-helm/pull/110

**Comment by denisa** [comment]
Not quite sure how this should be tested. Any advice?

**Comment by lachie83** [comment]
Sorry I missed this and thanks for taking the time to raise a PR. Fixed via https://github.com/lachie83/k8s-helm/pull/111
