### ISSUE TITLE
Version format

### ISSUE THREAD

**Issue by MaxenceAdnot** [lachie83/k8s-helm#20]
Hello,

Starting from 2.7.0 you changed the tag format. You previously defined your tags with the pattern vX.X.X but you pushed a version 2.7.0.

Is it something you want to keep, or will you push a v2.7.0 version ?
Note that Helm still uses vX.X.X as a pattern (they tagged the current release v2.7.0).

**Comment by ArchiFleKs** [comment]
I agree, could you stil push a "v2.7.0"  like the version format upstream ?

We use your image in Kubespray(https://github.com/kubernetes-incubator/kubespray) and it will be easier to maintain :)

**Comment by rsmitty** [comment]
@lachie83 would you happen to have any update on this? Any chance of getting the 2.7.0 docker image re-tagged? This would also match the tagging for other helm components like tiller (gcr.io/kubernetes-helm/tiller:v2.7.0)

**Comment by lachie83** [comment]
Oh wow! I just stumbled across this as I was out on paternity leave. So sorry. Of course. I will fix.

**Comment by lachie83** [comment]
Fixed! Thanks for raising this. Both tags are available just incase you're already using 2.7.0
