### ISSUE TITLE
Install plugin

### ISSUE THREAD

**Issue by kayotimoteo** [lachie83/k8s-helm#79]
Hello, I'm running the latest version and I'm getting the following error, could you help me?

`helm plugin install https://github.com/chartmuseum/helm-push.git`
 or 
`helm plugin install https://github.com/chartmuseum/helm-push.git --version 0.8.1`
and I get
`Error: git is not installed`
Thank you!

**Comment by lachie83** [comment]
Hi @kayotimoteo. Thank you for the suggestion. At this point I would like to keep this container tightly scoped only to Helm. Feel free to fork this repo and add the plugins you would like.
