### ISSUE TITLE
Helm v2.17.0 Fails test unable to connect to tiller.

### ISSUE THREAD

**Issue by Aurelian-Shuttleworth** [lachie83/k8s-helm#86]
Build for v2.17.0 is failing at the test step.

https://github.com/lachie83/k8s-helm/runs/1327502894

The solution is to add `-c` client flag to stop helm from checking the server version.

```
Flags:
  -c, --client                Client version only
```

**Comment by lachie83** [comment]
I believe this has been fixed.
